[build]
  base    = "/"
  publish = "build"
  command = "yarn install && yarn build"

[build.environment]
  NODE_VERSION = "12.13"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]

